export {
  triggerLightImpact,
  triggerMediumImpact,
  triggerHeavyImpact,
  triggerSuccess,
  triggerError,
  triggerWarning,
  hapticButtonPress,
  hapticAgeUp,
  hapticAchievement,
  hapticMoneyEarned,
  hapticNegativeEvent,
  hapticDecision,
  hapticMilestone,
  hapticDeath,
} from '@services/haptics';
