import { StyleSheet, Dimensions } from "react-native";

const { width } = Dimensions.get("window");

export const getCreateStyles = (
  radii: { sm: number; md: number; full: number; xs?: number },
  spacing: Record<string, number>,
  shadows: { subtle: object; card: object },
) =>
  StyleSheet.create({
    root: { flex: 1 },
    safe: { flex: 1 },
    header: {
      flexDirection: "row",
      alignItems: "center",
      paddingHorizontal: spacing.lg,
      paddingTop: spacing.md,
      paddingBottom: spacing.lg,
      borderBottomWidth: 1,
      marginBottom: spacing.xl,
    },
    backBtn: {
      width: 40,
      height: 40,
      borderRadius: radii.sm,
      alignItems: "center",
      justifyContent: "center",
      borderWidth: 1,
    },
    stepChapterLabel: { fontSize: 11 },
    stepChapterName: { fontSize: 15, marginTop: 2 },
    scroll: {
      flexGrow: 1,
      paddingHorizontal: spacing.xl,
      paddingBottom: spacing.md,
    },
    stepContainer: { gap: spacing.md },
    stepTitle: { fontSize: 28, marginTop: spacing.sm },
    stepSub: { fontSize: 14, lineHeight: 21, marginBottom: spacing.sm },
    inputLabel: {
      fontSize: 10,
      letterSpacing: 2,
      marginBottom: spacing.sm,
    },
    genderRow: { flexDirection: "row", gap: spacing.sm, marginBottom: spacing.lg },
    genderCard: {
      flex: 1,
      alignItems: "center",
      gap: spacing.xs,
      borderRadius: radii.md,
      padding: spacing.md,
      borderWidth: 2,
      ...shadows.subtle,
    },
    genderLabel: { fontSize: 13 },
    inputWrap: {
      flexDirection: "row",
      alignItems: "center",
      borderRadius: radii.md,
      borderWidth: 1.5,
      overflow: "hidden",
    },
    textInput: { fontSize: 16, paddingVertical: 15, paddingHorizontal: spacing.md, flex: 1 },
    countryChip: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
      paddingHorizontal: spacing.md,
      paddingVertical: spacing.sm,
      borderRadius: radii.full,
      borderWidth: 1.5,
    },
    countryFlag: { fontSize: 16 },
    countryName: { fontSize: 12 },
    bgGrid: { gap: spacing.sm },
    bgCard: {
      flexDirection: "row",
      alignItems: "center",
      gap: spacing.md,
      padding: spacing.md,
      borderRadius: radii.md,
      borderWidth: 2,
      position: "relative",
      overflow: "hidden",
      ...shadows.subtle,
    },
    bgIconWrap: {
      width: 44,
      height: 44,
      borderRadius: radii.sm,
      alignItems: "center",
      justifyContent: "center",
      flexShrink: 0,
    },
    bgLabel: { fontSize: 14 },
    bgDesc: { fontSize: 12, marginTop: 2 },
    wealthPill: {
      paddingHorizontal: 8,
      paddingVertical: 4,
      borderRadius: radii.full,
    },
    wealthText: { fontSize: 11 },
    activeTick: {
      position: "absolute",
      top: 8,
      right: 8,
      width: 20,
      height: 20,
      borderRadius: 10,
      alignItems: "center",
      justifyContent: "center",
    },
    zodiacGrid: { flexDirection: "row", flexWrap: "wrap", gap: spacing.sm },
    zodiacChip: {
      paddingHorizontal: spacing.md,
      paddingVertical: spacing.sm,
      borderRadius: radii.full,
      borderWidth: 1.5,
    },
    zodiacLabel: { fontSize: 13 },
    traitHint: {
      fontSize: 12,
      marginBottom: spacing.sm,
      marginTop: -spacing.sm,
    },
    traitGrid: { flexDirection: "row", flexWrap: "wrap", gap: spacing.sm },
    traitCard: {
      width: (width - spacing.xl * 2 - spacing.sm) / 2 - 0.5,
      padding: spacing.md,
      borderRadius: radii.md,
      borderWidth: 2,
      gap: 4,
      position: "relative",
      ...shadows.subtle,
    },
    traitCardLocked: { opacity: 0.4 },
    traitCheck: {
      position: "absolute",
      top: 8,
      right: 8,
      width: 18,
      height: 18,
      borderRadius: 9,
      alignItems: "center",
      justifyContent: "center",
    },
    traitLabel: { fontSize: 14 },
    traitDesc: { fontSize: 11 },
    ctaWrap: {
      paddingHorizontal: spacing.xl,
      paddingBottom: spacing.xl,
      paddingTop: spacing.md,
      borderTopWidth: 1,
    },
    spbWrap: { paddingHorizontal: spacing.lg, marginBottom: spacing.md },
    spbTrack: {
      height: 4,
      borderRadius: 2,
      overflow: "hidden",
      marginBottom: spacing.md,
    },
    spbFill: { height: "100%", borderRadius: 2 },
    spbDots: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
    },
    spbDot: {
      width: 28,
      height: 28,
      borderRadius: 14,
      borderWidth: 2,
      alignItems: "center",
      justifyContent: "center",
    },
    spbDotNum: { fontSize: 11 },
    spbConnector: {
      flex: 1,
      height: 2,
      marginHorizontal: 4,
      maxWidth: 40,
    },
    previewWrap: {
      paddingHorizontal: spacing.xl,
      marginBottom: spacing.md,
    },
    previewCard: {
      flexDirection: "row",
      alignItems: "center",
      gap: spacing.md,
      padding: spacing.md,
      borderRadius: radii.md,
      borderWidth: 2,
      ...shadows.subtle,
    },
    previewAvatarFrame: {
      width: 72,
      height: 72,
      borderRadius: 36,
      borderWidth: 2,
      overflow: "hidden",
      alignItems: "center",
      justifyContent: "center",
    },
    previewMeta: { flex: 1, gap: 4 },
    previewName: { fontSize: 16 },
    previewRow: { flexDirection: "row", alignItems: "center", flexWrap: "wrap", gap: 6 },
    previewChip: {
      paddingHorizontal: 8,
      paddingVertical: 2,
      borderRadius: radii.full,
    },
    previewChipText: { fontSize: 10 },
    previewTraitSummary: { fontSize: 11, lineHeight: 16 },
    economyPreviewCard: {
      flexDirection: "column",
      gap: spacing.sm,
      padding: spacing.md,
      borderRadius: radii.md,
      borderWidth: 1,
      ...shadows.subtle,
    },
    economyPreviewRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      gap: spacing.sm,
    },
    economyDetailsLink: {
      alignSelf: "flex-start",
      paddingVertical: spacing.xs,
    },
    originsSection: { gap: spacing.sm },
    originsSectionHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingVertical: spacing.xs,
    },
    originsSectionBody: { gap: spacing.sm },
    regionTabBar: { flexDirection: "row", gap: spacing.xs },
    regionTab: {
      paddingHorizontal: spacing.md,
      paddingVertical: spacing.sm,
      borderRadius: radii.full,
      borderWidth: 1.5,
    },
  });
